## 原理剖析

关于异常，我们需要知晓有一个异常表的存在，`try`的范围就是体现在异常表行记录的起点和终点。
JVM在`try`住的代码区间内如有异常抛出的话，就会在当前栈桢的异常表中，找到匹配类型的异常记录的入口指令号，然后跳到该指令处执行。
异常指令块执行完后，再回来继续执行后面的代码。
JVM按照每个入口在表中出现的顺序进行检索，如果没有发现匹配的项，JVM将当前栈帧从栈中弹出，再次抛出同样的异常。
当JVM弹出当前栈帧时，JVM马上终止当前方法的执行，并且返回到调用本方法的方法中，
但是并非继续正常执行该方法，而是在该方法中抛出同样的异常，这就使得JVM在该方法中再次执行同样的搜寻异常表的操作。

上面那样的内层方法无法处理异常的层层向外抛，层层压栈，这样就形成一个异常栈。
异常栈十分有利于我们分析问题之所在，例如`e.printStackTrace();`或者带参数的`e.printStackTrace(PrintStream s);`方法可将异常栈信息定向输出到他处，
还有`log4j`的`log.error(Throwable)`也有此功效。
若是在行径的哪层有能力处理该异常则已，否则直至JVM，直接造成JVM崩溃掉。例如当`main()`方法也把异常抛了出去，JVM此刻也就到了生命的尽头。

## 异常吞噬问题

以下代码执行之后，会直接返回false，且不会将异常抛出。

```java
boolean test() {
    try {
        int b = 2/0
        return true;
    } catch (Exception e) {
        System.out.println("catch is executed");
        throw e;
    } finally {
        System.out.println("finally is executed");
        return false;
    }
}
```